# Generated by Django 5.2.5 on 2025-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_wallet_public_key_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='wallet_address',
            new_name='hedera_account_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_public_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hedera_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WalletNonce',
        ),
    ]
