# Generated by Django 5.2.5 on 2025-09-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_wallet_address_customuser_hedera_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hedera_account_id',
            field=models.CharField(blank=True, help_text='Optional Hedera account id ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text='Optional emoji or image id for UI', max_length=255),
        ),
    ]
